
# Pterodactyl Panel Information:
panelDomain: "panelurl.net"
clientKey: "ptlc_FAKEKEYWILLNOTWORK"

# servers
categories:
- name: "Ducktown"
  servers:
    - name: "Donald"      # AUS 01 Moon
      id: "dd15f315"
    - name: "Mickey"      # AUS 02 Sun
      id: "42aa13a2"
- name: "Cats"
  servers:
    - name: "Tom"         # CAN 01 Mango
      id: "2eb9bf30"
    - name: "Topcat"      # CAN 02 Pine
      id: "94c1e340"
- name: "Dogs"
  servers:
    - name: "Pluto"       # EUR 01 Venus
      id: "c92c7882"
    - name: "Scooby Doo"  # EUR 02 Hercules
      id: "9a1c0741"
    - name: "Ren"         # EUR 03 Olympia
      id: "e83c06f5"
- name: "Other"
  servers:
    - name: "Tweetie"     # SGP 01 Bowtruckle
      id: "bd8f5d1e"
    - name: "Jerry"       # SGP 02 Niffler
      id: "8a16850b"
    - name: "Pinkie"      # SGP 03 Nundu
      id: "1d5b9b6f"
    - name: "Brain"       # SGP 04 Doxy
      id: "c0716643"
